Fix issue around Reveal not being able to publish service
Reveal uses Bonjour to publish the service. Starting in iOS 14, apps are required to provide a privacy usage description for accessing the local network, which includes browsing and advertising Bonjour services. Without this, the Reveal server fails to publish the Bonjour service:

	ERROR: Reveal Server failed to publish service via Bonjour. Error: Error Domain=com.ittybittyapps.IBANetServicesErrorDomain Code=-65555 "No auth." UserInfo={NSLocalizedFailureReason=No auth.}